/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.politecnicomalaga.ejercicio_var_4;

public class App {
    
    public static void main(String[] args) {
        
        String nombre = "Ángel García Aguilera";
        String direccion="C/ Magistrado Salvador Barbera, 3";
        String telefono="694423339";
        
        System.out.println("Nombre: " + nombre);
        System.out.println("Dirección: " + direccion);
        System.out.println("Teléfono: " + telefono);
    }
}
